# =============================================================================
# OpenPay Worker Service — Application Configuration
# =============================================================================

spring:
  datasource:
    # --- PostgreSQL Connection (reuse same DB as API service) ---
    url: jdbc:postgresql://localhost:5432/openpay_db # JDBC URL for Postgres
    username: postgres # Database username
    password: PG@admin2800 # Database password (change for prod!)
    driver-class-name: org.postgresql.Driver # JDBC driver

    # --- HikariCP Pool ---
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate # Validate schema (no updates/drops in prod!)
    show-sql: true # Show SQL queries (disable for prod)
    properties:
      hibernate.format_sql: true # Pretty SQL for logs

  flyway:
    enabled: true # DB migration management (Flyway)
    baseline-on-migrate: true
    locations: classpath:db/migration # Migration scripts location

  data:
    redis:
      host: 127.0.0.1 # Redis server (update for prod)
      port: 6379
      database: 0
      # password: your_password_here     # Set if Redis uses auth in prod
      timeout: 2000
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1

server:
  port: 8081 # Worker usually runs as headless/background; no HTTP by default

logging:
  level:
    root: INFO
    "[org.springframework.data.redis]": DEBUG # Show Redis ops for troubleshooting (set to INFO in prod)

# =============================================================================
# Notes:
# - Use a separate port to avoid clash with API service.
# - Make sure DB/Redis creds are secured for prod deployments.
# - Use log aggregation/alerting for worker logs in prod.
# =============================================================================
